# Generated by Django 6.0.1 on 2026-01-20 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='calorias_quemadas',
            field=models.PositiveIntegerField(help_text='Calorías quemadas durante la actividad', null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
