# Generated by Django 6.0.1 on 2026-02-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0003_tipoejercicio_remove_actividad_calorias_quemadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='series',
        ),
    ]
