# Generated by Django 6.0.1 on 2026-02-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0004_remove_ejercicio_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='repeticiones',
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='exampleapp.ejercicio')),
            ],
        ),
    ]
